substitutions:
  name: tx-ultimate-easy
  friendly_name: TX Ultimate Easy

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  remote_package:
    url: https://github.com/edwardtfn/TX-Ultimate-Easy
    ref: dev
    refresh: 1h
    files:
      - ESPHome/TX-Ultimate-Easy-ESPHome_core.yaml

### Uncomment the lines bellow if you have issues with OTA and cannot flash via serial at this moment. ###
#esp32:
#  flash_size: 4MB
