---
packages:
  basic_package: !include ../TX-Ultimate-Easy-ESPHome.yaml  # Core package
  addon_bluetooth_proxy: !include ../ESPHome/TX-Ultimate-Easy-ESPHome_addon_ble_proxy.yaml

esp32:
  framework:
    type: esp-idf
    version: 5.0.2
    platform_version: 6.3.2
...
