# yamllint disable rule:document-start rule:document-end rule:new-line-at-end-of-file
platform: partition
default_transition_length: ${default_transition_length}
# yamllint enable rule:document-start rule:document-end rule:new-line-at-end-of-file
