# This GitHub Actions workflow updates the "stable" and "latest" Git tags
# to point to the tag associated with a newly published release. It performs
# the following steps:
# 1. Checks out the repository code with full history.
# 2. Configures Git with a generic user for the action.
# 3. Moves and forcibly pushes the "stable" and "latest" tags to align with
#    the tag of the newly published release.
# This ensures that "stable" and "latest" always point to the most recent release.
---
name: Update Tags

# yamllint disable-line rule:truthy
on:
  release:
    types: [published]

jobs:
  update-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: '0'

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Move and push stable tag
        run: |
          git tag -f stable ${{ github.event.release.tag_name }}
          git push -f origin stable

      - name: Move and push latest tag
        run: |
          git tag -f latest ${{ github.event.release.tag_name }}
          git push -f origin latest
...
