---
name: Validate C++ (Clang Format)

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '**/*.h'
      - '**/*.c'
      - '**/*.cpp'
  pull_request:
    paths:
      - '**/*.h'
      - '**/*.c'
      - '**/*.cpp'
  workflow_dispatch:

jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: RafikFarhad/clang-format-github-action@v3
        with:
          sources: "components/tx_ultimate_easy/*.h,components/tx_ultimate_easy/*.cpp"
...
