# Workflow for managing versioning, tagging, and conditional updates
---
name: Bump Version and Tag

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      update_stable:
        description: "Update stable tag?"
        required: true
        default: "false"

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Bump Version
        run: |
          chmod +x ./versioning/bump_version.sh
          ./versioning/bump_version.sh

      - name: Push Changes and Tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git push origin main; then
            echo "Failed to push to main branch"
            exit 1
          fi
          if ! git push origin --tags --force; then
            echo "Failed to push tags"
            exit 1
          fi

      - name: Conditionally Update Stable Tag
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.update_stable == 'true' }}
        run: |
          git tag -f stable
          git push origin stable --force
...
