# Workflow for managing versioning and tagging
---
name: Version Bump and Tag

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths-ignore:
      - '**/VERSION'
      - '**/VERSION_YAML'
  workflow_dispatch:
    inputs:
      update_stable:
        description: "Update stable tag?"
        required: true
        default: "false"

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v4"

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Bump Version
        run: |
          chmod +x "./versioning/bump_version.sh"
          "./versioning/bump_version.sh"

      - name: Push Changes and Tags
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" --tags
...
